import Data.List

replaceAll :: (String,[String]) -> String -> [String]
replaceAll (replace_this,by_these) = go
  where go [] = [""]
        go s
          | replace_this `isPrefixOf` s =
            concat [map (++sfx) by_these | sfx <- go (drop (length replace_this) s)]
          | otherwise = map (head s:) (go (tail s))

vs =
 ["CMAKE_COMPILER_IS_GNU<LANG>",
  "CMAKE_Fortran_MODDIR_DEFAULT",
  "CMAKE_Fortran_MODDIR_FLAG",
  "CMAKE_Fortran_MODOUT_FLAG",
  "CMAKE_INTERNAL_PLATFORM_ABI",
  "CMAKE_<LANG>_ARCHIVE_APPEND",
  "CMAKE_<LANG>_ARCHIVE_CREATE",
  "CMAKE_<LANG>_ARCHIVE_FINISH",
  "CMAKE_<LANG>_COMPILE_OBJECT",
  "CMAKE_<LANG>_COMPILER_ABI",
  "CMAKE_<LANG>_COMPILER_ID",
  "CMAKE_<LANG>_COMPILER_LOADED",
  "CMAKE_<LANG>_COMPILER",
  "CMAKE_<LANG>_COMPILER_EXTERNAL_TOOLCHAIN",
  "CMAKE_<LANG>_COMPILER_TARGET",
  "CMAKE_<LANG>_COMPILER_VERSION",
  "CMAKE_<LANG>_CREATE_SHARED_LIBRARY",
  "CMAKE_<LANG>_CREATE_SHARED_MODULE",
  "CMAKE_<LANG>_CREATE_STATIC_LIBRARY",
  "CMAKE_<LANG>_FLAGS_DEBUG",
  "CMAKE_<LANG>_FLAGS_MINSIZEREL",
  "CMAKE_<LANG>_FLAGS_RELEASE",
  "CMAKE_<LANG>_FLAGS_RELWITHDEBINFO",
  "CMAKE_<LANG>_FLAGS",
  "CMAKE_<LANG>_IGNORE_EXTENSIONS",
  "CMAKE_<LANG>_IMPLICIT_INCLUDE_DIRECTORIES",
  "CMAKE_<LANG>_IMPLICIT_LINK_DIRECTORIES",
  "CMAKE_<LANG>_IMPLICIT_LINK_FRAMEWORK_DIRECTORIES",
  "CMAKE_<LANG>_IMPLICIT_LINK_LIBRARIES",
  "CMAKE_<LANG>_LIBRARY_ARCHITECTURE",
  "CMAKE_<LANG>_LINKER_PREFERENCE_PROPAGATES",
  "CMAKE_<LANG>_LINKER_PREFERENCE",
  "CMAKE_<LANG>_LINK_EXECUTABLE",
  "CMAKE_<LANG>_OUTPUT_EXTENSION",
  "CMAKE_<LANG>_PLATFORM_ID",
  "CMAKE_<LANG>_SIMULATE_ID",
  "CMAKE_<LANG>_SIMULATE_VERSION",
  "CMAKE_<LANG>_SIZEOF_DATA_PTR",
  "CMAKE_<LANG>_SOURCE_FILE_EXTENSIONS",
  "CMAKE_USER_MAKE_RULES_OVERRIDE_<LANG>"]